remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: [Source Paralegal]
description: [Virtualized paralegal support services]
logo: assets/images/source-paralegal-logo.jpeg
page1: [paralegalservices]
page1description: [Services Offered]
source: app
